# Encoding: UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ nombre: 'Chicago' }, { nombre: 'Copenhagen' }])
#   Mayor.create(nombre: 'Emanuel', city: cities.first)

Usuario.create([
  {nombre: 'gua.her03', contrasena: 'ghuear03'},
  {nombre: 'gua.ver02', contrasena: 'gvuear02'},
  {nombre: 'alf.ver03', contrasena: 'avlefr03'},
  {nombre: 'bre.ver02', contrasena: 'bvreer02'},
  {nombre: 'sot.agu02', contrasena: 'saogtu02'},
  {nombre: 'kar.jul01', contrasena: 'kjaurl01'},
  {nombre: 'cat.lec02', contrasena: 'claetc02'},
  {nombre: 'uri.roz02', contrasena: 'urroiz02'},
  {nombre: 'oli.rey02', contrasena: 'orleiy02'},
  {nombre: 'cac.piz02', contrasena: 'cpaicz02'},
  {nombre: 'sub.tol02', contrasena: 'stuobl02'},
  {nombre: 'ver.bra06', contrasena: 'vberra06'},
  {nombre: 'ver.fic04', contrasena: 'vfeirc04'},
  {nombre: 'ver.ver02', contrasena: 'vveerr02'},
  {nombre: 'val.val02', contrasena: 'vvaall02'},
  {nombre: 'ver.oqu02', contrasena: 'voeqru02'},
  {nombre: 'cas.ana03', contrasena: 'caansa03'},
  {nombre: 'ver.nun02', contrasena: 'vneurn02'},
  {nombre: 'ver.rev03', contrasena: 'vreerv03'},
  {nombre: 'necita01', contrasena: 'nietca01'},
  {nombre: 'cru.cab02', contrasena: 'ccraub02'},
  {nombre: 'and.zam01', contrasena: 'aznadm01'},
  {nombre: 'gua.vil06', contrasena: 'gvuial06'},
  {nombre: 'zam.dur02', contrasena: 'zdaumr02'},
  {nombre: 'ang.gua01', contrasena: 'agnuga01'},
  {nombre: 'gua.mor03', contrasena: 'gmuoar03'},
  {nombre: 'ver.sol03', contrasena: 'vseorl03'},
  {nombre: 'val.alv04', contrasena: 'vaallv04'},
  {nombre: 'val.san03', contrasena: 'vsaaln03'},
  {nombre: 'val.agu02', contrasena: 'vaaglu02'},
  {nombre: 'gab.gil01', contrasena: 'ggaibl01'},
  {nombre: 'men.leo02', contrasena: 'mleeno02'},
  {nombre: 'med.rob02', contrasena: 'mreodb02'},
  {nombre: 'san.val02', contrasena: 'svaanl02'},
  {nombre: 'sam.nis01', contrasena: 'snaims01'},
  {nombre: 'thi.mel01', contrasena: 'tmheil01'},
  {nombre: 'pri.hoy01', contrasena: 'phroiy01'},
  {nombre: 'jes.arr02', contrasena: 'jaersr02'},
  {nombre: 'mar.gua01', contrasena: 'mgaura01'},
  {nombre: 'juani', contrasena: 'inauj01'},
  {nombre: 'jul.gua01', contrasena: 'jguula01'},
  {nombre: 'med.fue02', contrasena: 'mfeude02'},
  {nombre: 'mor.dia02', contrasena: 'mdoira02'},
  {nombre: 'bur.poc02', contrasena: 'bpuorc02'},
  {nombre: 'sep.sae02', contrasena: 'sseape02'},
  {nombre: 'ara.mun02', contrasena: 'amruan02'},
  {nombre: 'cif.var02', contrasena: 'cviafr02'},
  {nombre: 'ale.leo01', contrasena: 'alleeo'},
  {nombre: 'jav.rob02', contrasena: 'jraovb02'},
  {nombre: 'pat.bor01', contrasena: 'pbaotr01'},
  {nombre: 'dia.vas01', contrasena: 'dviaas01'},
  {nombre: 'maz.nom02', contrasena: 'mnaozm02'},
  {nombre: 'ana.abr01', contrasena: 'aanbar01'},
  {nombre: 'con.cha02', contrasena: 'ccohna02'},
  {nombre: 'mar.gal01', contrasena: 'mgaarl01'},
  {nombre: 'luc.all01', contrasena: 'laulcl01'},
  {nombre: 'tal.nav01', contrasena: 'tnaalv01'},
  {nombre: 'jug.elg01', contrasena: 'jeulgg01'},
  {nombre: 'iva.leo01', contrasena: 'ilveao01'},
  {nombre: 'ala.tar02', contrasena: 'atlaar02'},
  {nombre: 'mar.flo01', contrasena: 'mfalro01'},
  {nombre: 'jos.moy01', contrasena: 'jmoosy01'},
  {nombre: 'pom.por02', contrasena: 'ppoomr02'},
  {nombre: 'del.bri02', contrasena: 'dberli02'},
  {nombre: 'paz.roj01', contrasena: 'praozj01'},
  {nombre: 'mac.men01', contrasena: 'mmaecn01'},
  {nombre: 'mar.her01', contrasena: 'mhaerr01'},
  {nombre: 'ing.may01', contrasena: 'imnagy01'},
  {nombre: 'ign.man01', contrasena: 'imgann01'},
  {nombre: 'pen.nun02', contrasena: 'pneunn02'},
  {nombre: 'nun.dro02', contrasena: 'ndurno02'},
  {nombre: 'and.pur01', contrasena: 'apnudr01'},
  {nombre: 'alv.hin01', contrasena: 'ahlivn01'},
  {nombre: 'cas.sal02', contrasena: 'csaasl02'},
  {nombre: 'sal.cas02', contrasena: 'scaals02'},
  {nombre: 'cas.lea02', contrasena: 'claesa02'},
  {nombre: 'gar.hui01', contrasena: 'ghauri01'},
  {nombre: 'pab.dur02', contrasena: 'pdaubr02'},
  {nombre: 'kat.mar02', contrasena: 'kmaatr02'},
  {nombre: 'arr.rey02', contrasena: 'arrery02'},
  {nombre: 'ace.sal03', contrasena: 'ascael03'},
  {nombre: 'arr.ace02', contrasena: 'aarcre02'},
  {nombre: 'fra.ace01', contrasena: 'farcae01'},
  {nombre: 'ace.del05', contrasena: 'adceel05'},
  {nombre: 'rio.ace02', contrasena: 'raicoe02'},
  {nombre: 'jua.ser01', contrasena: 'jsuear01'},
  {nombre: 'sil.par07', contrasena: 'spialr07'},
  {nombre: 'val.san02', contrasena: 'vsaaln02'},
  {nombre: 'gut.fue02', contrasena: 'gfuute02'},
  {nombre: 'ace.car02', contrasena: 'accaer02'},
  {nombre: 'lia.arr01', contrasena: 'lairar01'},
  {nombre: 'ven.ver02', contrasena: 'vveenr02'},
  {nombre: 'car.var02', contrasena: 'cvaarr02'},
  {nombre: 'arr.var03', contrasena: 'avrarr03'},
  {nombre: 'ema.arr01', contrasena: 'eamrar01'},
  {nombre: 'gar.car02', contrasena: 'gcaarr02'},
  {nombre: 'faj.esq02', contrasena: 'feasjq02'},
  {nombre: 'guz.zap02', contrasena: 'gzuazp02'},
  {nombre: 'car.est02', contrasena: 'ceasrt02'},
  {nombre: 'yur.cif01', contrasena: 'ycuirf01'},
  {nombre: 'ace.chi02', contrasena: 'acchei02'},
  {nombre: 'tom.and01', contrasena: 'taonmd01'},
  {nombre: 'sil.gar02', contrasena: 'sgialr02'},
  {nombre: 'ser.zor02', contrasena: 'szeorz02'},
  {nombre: 'fer.med01', contrasena: 'fmeerd01'},
  {nombre: 'jul.arm01', contrasena: 'jaurlm01'},
  {nombre: 'gon.nun02', contrasena: 'gnounn02'},
  {nombre: 'pum.bad02', contrasena: 'pbuamd02'},
  {nombre: 'car.qui02', contrasena: 'cqauri02'},
  {nombre: 'bus.ros02', contrasena: 'bruoss02'},
  {nombre: 'jav.gut02', contrasena: 'jgauvt02'},
  {nombre: 'vic.paz01', contrasena: 'vpiacz01'},
  {nombre: 'can.dor02', contrasena: 'cdaonr02'},
  {nombre: 'lei.laa01', contrasena: 'lleaia01'},
  {nombre: 'jua.ore01', contrasena: 'jourae01'},
  {nombre: 'lar.sal02', contrasena: 'lsaarl02'},
  {nombre: 'mar.lar01', contrasena: 'mlaarr01'},
  {nombre: 'paula01', contrasena: 'aluap01'},
  {nombre: 'tit.ven01', contrasena: 'tvietn01'},
  {nombre: 'viv.ven01', contrasena: 'vvievn01'},
  {nombre: 'acu.wag02', contrasena: 'awcaug02'},
  {nombre: 'pau.ham01', contrasena: 'phaaum01'},
  {nombre: 'dev.dev02', contrasena: 'ddeevv02'},
  {nombre: 'eng.eng02', contrasena: 'eenngg02'},
  {nombre: 'wag.wag02', contrasena: 'wwaagg02'},
  {nombre: 'alv.men02', contrasena: 'amlevn02'},
  {nombre: 'mar.gut02', contrasena: 'mgaurt02'},
  {nombre: 'nic.gut02', contrasena: 'ngiuct02'},
  {nombre: 'fre.cur02', contrasena: 'fcruer02'},
  {nombre: 'pob.tor02', contrasena: 'ptoobr02'},
  {nombre: 'mar.arr02', contrasena: 'maarrr02'},
  {nombre: 'hil.esp01', contrasena: 'heislp01'},
  {nombre: 'ade.rey02', contrasena: 'ardeey02'},
  {nombre: 'jua.jaq01', contrasena: 'jjuaaq01'}
])

Regalo.create([
  {detalle: 'Pasaje Santiago -Paris -Santiago (1/8)', cantidad: 1, precio_pesos_chilenos: 84835},
  {detalle: 'Eurorail 5 Países (1/4)', cantidad: 1, precio_pesos_chilenos: 47235},
  {detalle: 'Eurorail 2 Países (1/2)', cantidad: 1, precio_pesos_chilenos: 43710},
  {detalle: 'Eurorail 1 País', cantidad: 1, precio_pesos_chilenos: 23970},
  {detalle: 'AirfranceBus 1', cantidad: 2, precio_pesos_chilenos: 19740},
  {detalle: 'Billet Paris - Saint Malo - Paris', cantidad: 1, precio_pesos_chilenos: 46319},
  {detalle: 'Pantheon', cantidad: 2, precio_pesos_chilenos: 10575},
  {detalle: 'Musée Rodin', cantidad: 2, precio_pesos_chilenos: 12690},
  {detalle: 'Musée Du Quai Branly', cantidad: 2, precio_pesos_chilenos: 11985},
  {detalle: 'Catacombes', cantidad: 2, precio_pesos_chilenos: 9870},
  {detalle: 'Arc de Triomphe', cantidad: 2, precio_pesos_chilenos: 12690},
  {detalle: 'Centre Pompidou / Musée D\'Art Moderne', cantidad: 2, precio_pesos_chilenos: 14100},
  {detalle: 'Musée de Louvre', cantidad: 2, precio_pesos_chilenos: 18330},
  {detalle: 'DisneyLand Paris Passe partout', cantidad: 2, precio_pesos_chilenos: 78960},
  {detalle: 'Alimentación x 5 días', cantidad: 1, precio_pesos_chilenos: 50000},
  {detalle: 'Alimentación x 10 días', cantidad: 1, precio_pesos_chilenos: 100000},
  {detalle: 'Alimentación x 15 días', cantidad: 1, precio_pesos_chilenos: 150000},
  {detalle: 'Museo Thyssen Bornemisza', cantidad: 2, precio_pesos_chilenos: 8460},
  {detalle: 'Museo del Prado', cantidad: 2, precio_pesos_chilenos: 14100},
  {detalle: 'Centro de Arte Reina Sofia', cantidad: 2, precio_pesos_chilenos: 8460},
  {detalle: 'Billete 10 viajes Combinado Metro', cantidad: 1, precio_pesos_chilenos: 21150},
  {detalle: 'Vista Coliseo', cantidad: 2, precio_pesos_chilenos: 15510},
  {detalle: 'Museo Vaticano', cantidad: 2, precio_pesos_chilenos: 19740},
  {detalle: 'Castillo Saint-Angelo', cantidad: 2, precio_pesos_chilenos: 9870},
  {detalle: 'Piazza del Campidoglio / Musei Capitolini', cantidad: 2, precio_pesos_chilenos: 9165},
  {detalle: 'Museo Nazionale Romano', cantidad: 2, precio_pesos_chilenos: 9870},
  {detalle: 'Catacumbas de San Calisto', cantidad: 2, precio_pesos_chilenos: 7050},
  {detalle: 'Terme di Caracalla', cantidad: 2, precio_pesos_chilenos: 8460},
  {detalle: 'Galleria Nazionale d\'arte antica', cantidad: 2, precio_pesos_chilenos: 7050},
  {detalle: 'BTI-Ticket Turista Integrado', cantidad: 2, precio_pesos_chilenos: 15510},
  {detalle: 'Palazzo Ducale', cantidad: 2, precio_pesos_chilenos: 16920},
  {detalle: 'Collezione Peggy Guggenheim', cantidad: 2, precio_pesos_chilenos: 14100},
  {detalle: 'Palazzo Grassi', cantidad: 2, precio_pesos_chilenos: 14100},
  {detalle: 'Hotel Bernardi', cantidad: 1, precio_pesos_chilenos: 38775},
  {detalle: 'Ristorante La Bitta', cantidad: 1, precio_pesos_chilenos: 28200},
  {detalle: 'Ristoteca Oniga', cantidad: 1, precio_pesos_chilenos: 32430},
  {detalle: 'Promenade Gondola', cantidad: 1, precio_pesos_chilenos: 17625},
  {detalle: 'Amsterdam Card 24 hrs', cantidad: 1, precio_pesos_chilenos: 23265},
  {detalle: 'Amsterdam Card 48 hrs', cantidad: 1, precio_pesos_chilenos: 30315},
  {detalle: 'Amsterdam Card 72 hrs', cantidad: 1, precio_pesos_chilenos: 37365},
  {detalle: 'Nieuwe kerk', cantidad: 2, precio_pesos_chilenos: 5640},
  {detalle: 'Oude Kerk', cantidad: 2, precio_pesos_chilenos: 7050},
  {detalle: 'Amsterdams Historish Museum', cantidad: 2, precio_pesos_chilenos: 14100},
  {detalle: 'Museum Het Rembrandthuis', cantidad: 2, precio_pesos_chilenos: 11280},
  {detalle: 'Anne Frank Huis', cantidad: 2, precio_pesos_chilenos: 11985},
  {detalle: 'FOAM', cantidad: 2, precio_pesos_chilenos: 9870},
  {detalle: 'Rijksmuseum', cantidad: 2, precio_pesos_chilenos: 14100},
  {detalle: 'Artis', cantidad: 1, precio_pesos_chilenos: 12690},
  {detalle: 'Quentin Hotel', cantidad: 1, precio_pesos_chilenos: 31725},
  {detalle: 'Hotel Nadia', cantidad: 1, precio_pesos_chilenos: 38775},
  {detalle: 'Canal Bus', cantidad: 1, precio_pesos_chilenos: 12690}
])